FROM node:18-alpine AS base
WORKDIR /app
ENV NODE_ENV production
COPY package.json yarn.lock ./
RUN yarn

FROM base AS build
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

RUN yarn run prisma:generate
RUN yarn build

FROM base AS deploy

COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

EXPOSE 3000

ENV PORT 3000

CMD ["node", "server.js"]